server {
    listen 80;

    root /usr/share/nginx/html;

    location = /client/v4/ips {
        try_files /ips.json =404;
    }
    location = /health {
        access_log off;
        return 200;
    }
    location / {
        return 404;
    }
}
