package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"senthora.com/edge-trust/internal/testutil"
)

//goland:noinspection GoUnhandledErrorResult
func TestGenerateTrustedProxyConfig_HappyPath(t *testing.T) {
	ips := []string{
		"1.1.1.0/24",
		"2606:4700::/32",
	}
	//goland:noinspection HttpUrlsUsage
	sourceUrl := "http://example.com"
	now, nowFormat := timeNow()

	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by edge-trust at: %s\n", nowFormat)
	fmt.Fprintf(&b, "# Source: %s\n", sourceUrl)
	fmt.Fprintf(&b, "# Total IPs: %d\n\n", len(ips))

	for _, ip := range ips {
		fmt.Fprintf(&b, "set_real_ip_from %s;\n", ip)
	}
	expected := b.String()
	actual := GenerateTrustedProxyConfig(ips, sourceUrl, now)

	assertConfigContent(t, actual, expected)
}

//goland:noinspection GoUnhandledErrorResult
func TestGenerateTrustedProxyConfig_EmptyInput(t *testing.T) {
	var ips []string
	//goland:noinspection HttpUrlsUsage
	sourceUrl := "http://example.com"
	now, nowFormat := timeNow()

	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by edge-trust at: %s\n", nowFormat)
	fmt.Fprintf(&b, "# Source: %s\n", sourceUrl)
	b.WriteString("# Total IPs: 0\n\n")

	expected := b.String()
	actual := GenerateTrustedProxyConfig(ips, sourceUrl, now)

	assertConfigContent(t, actual, expected)
}

//goland:noinspection GoUnhandledErrorResult
func TestGenerateOriginAllowlistConfig_HappyPath(t *testing.T) {
	ips := []string{
		"1.1.1.0/24",
		"2606:4700::/32",
	}
	//goland:noinspection HttpUrlsUsage
	sourceUrl := "http://example.com"
	now, nowFormat := timeNow()

	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by edge-trust at: %s\n", nowFormat)
	fmt.Fprintf(&b, "# Source: %s\n", sourceUrl)
	fmt.Fprintf(&b, "# Total IPs: %d\n\n", len(ips))

	for _, ip := range ips {
		fmt.Fprintf(&b, "%s 1;\n", ip)
	}
	b.WriteString("\n")

	expected := b.String()
	actual := GenerateOriginAllowlistConfig(ips, sourceUrl, now)

	assertConfigContent(t, actual, expected)
}

//goland:noinspection GoUnhandledErrorResult
func TestGenerateOriginAllowlistConfig_EmptyInput(t *testing.T) {
	var ips []string
	//goland:noinspection HttpUrlsUsage
	sourceUrl := "http://example.com"
	now, nowFormat := timeNow()

	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by edge-trust at: %s\n", nowFormat)
	fmt.Fprintf(&b, "# Source: %s\n", sourceUrl)
	b.WriteString("# Total IPs: 0\n\n")

	b.WriteString("\n")

	expected := b.String()
	actual := GenerateOriginAllowlistConfig(ips, sourceUrl, now)

	assertConfigContent(t, actual, expected)
}

func TestWriteConfig_CreatesFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nginx.conf")
	log := testutil.NewLogger()

	config := Config{content: "hello world"}

	err := config.Write(log, path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read file: %v", err)
	}
	assertConfigContent(t, config, string(data))
}

func TestWriteConfig_OverwritesFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nginx.conf")
	log := testutil.NewLogger()

	err := os.WriteFile(path, []byte("old content"), 0644)
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	newContent := "new content"
	config := Config{content: newContent}

	err = config.Write(log, path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read file: %v", err)
	}
	assertConfigContent(t, config, string(data))
}

func timeNow() (time.Time, string) {
	now := testutil.FixedTimeNowUTC()
	return now, now.UTC().Format(time.RFC3339)
}

func assertConfigContent(t *testing.T, config Config, expected string) {
	t.Helper()

	if config.content != expected {
		t.Fatalf("unexpected content: got %q, want %q", config.content, expected)
	}
}
