package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"go.uber.org/zap"
	"senthora.com/edge-trust/internal/fsutil"
)

type Config struct {
	content string
}

// GenerateTrustedProxyConfig takes a list of trusted proxy
// CIDR ranges and returns nginx real IP configuration.
func GenerateTrustedProxyConfig(ips []string, sourceUrl string, now time.Time) Config {
	b := configTemplate(now, sourceUrl, len(ips))

	for _, ip := range ips {
		b.WriteString("set_real_ip_from ")
		b.WriteString(ip)
		b.WriteString(";\n")
	}
	return Config{
		content: b.String(),
	}
}

// GenerateOriginAllowlistConfig takes a list of IP CIDR
// ranges and returns nginx Cloudflare allowlist mappings.
func GenerateOriginAllowlistConfig(ips []string, sourceUrl string, now time.Time) Config {
	b := configTemplate(now, sourceUrl, len(ips))

	for _, ip := range ips {
		b.WriteString(ip)
		b.WriteString(" 1;\n")
	}
	b.WriteString("\n")

	return Config{
		content: b.String(),
	}
}

// Write writes the nginx configuration content to the
// specified file path, overwriting if it exists or creating it otherwise.
func (c *Config) Write(logger *zap.Logger, path string) error {
	dirPath := filepath.Dir(path)
	if !dirExists(dirPath) {
		logger.Debug("creating directory", zap.String("path", dirPath))
		err := os.MkdirAll(dirPath, 0755)
		if err != nil {
			return fmt.Errorf("create config directory %q: %w", dirPath, err)
		}
	}
	if err := fsutil.WriteFileAtomic(logger, path, []byte(c.content)); err != nil {
		return fmt.Errorf("write config file %q: %w", path, err)
	}
	return nil
}

func configTemplate(now time.Time, sourceUrl string, totalIps int) *strings.Builder {
	var b strings.Builder

	b.WriteString("# Generated by edge-trust at: ")
	b.WriteString(now.UTC().Format(time.RFC3339))
	b.WriteString("\n")

	b.WriteString("# Source: ")
	b.WriteString(sourceUrl)
	b.WriteString("\n")

	b.WriteString("# Total IPs: ")
	b.WriteString(strconv.Itoa(totalIps))
	b.WriteString("\n\n")

	return &b
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}
